config/routes.rb
ResetpasswordSorcery::Application.routes.draw do
  
  get 'logout' => 'sessions#destroy', as: :logout

  resources :sessions
  resources :users
  resources :password_resets

  root 'users#index'

  

end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController

  def new
    
  end
  # request password reset.
  # you get here when the user entered his email in the reset password form and submitted it.
  def create 
    @user = User.find_by( email: params[:email] )
    if @user
      flash[:error] = "#{@user.username}"
    else
      flash[:error] = "nada"
    end
    # This line sends an email to the user with instructions on how to reset their password (a url with a random token)
    @user.deliver_reset_password_instructions! if @user
        
    # Tell the user instructions have been sent whether or not email was found.
    # This is to not leak information to attackers about which emails exist in the system.
    redirect_to(root_path, :notice => 'Instructions have been sent to your email.')
  end
    
  # This is the reset password form.
  def edit
    @user = User.load_from_reset_password_token(params[:id])
    @token = params[:id]

    if @user.blank?
      not_authenticated
      return
    end
  end
      
  # This action fires when the user has sent the reset password form.
  def update
    @token = params[:token]
    @user = User.load_from_reset_password_token(params[:token])

    if @user.blank?
      not_authenticated
      return
    end

    # the next line makes the password confirmation validation work
    @user.password_confirmation = params[:user][:password_confirmation]
    # the next line clears the temporary token and updates the password
    if @user.change_password!(params[:user][:password])
      redirect_to(root_path, :notice => 'Password was successfully updated.')
    else
      render :action => "edit"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = login( params[:username], params[:password], params[:remember_me] )

  	if user
  		redirect_to root_url
  	else
  		render :new
  	end
  end

  def destroy
  	logout
  	redirect_to root_url
  end

  private
	  def session_params
	  	params.permit( :username, :password, :remember_me )
	  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :get_user, only: [:show, :edit, :update, :destroy]

	def index
		@users = User.all
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new( user_params )

		if @user.save
			redirect_to root_url
		else
			render :new
		end
	end

	def show
		
	end

	def edit
		
	end

	def update
		if @user.update( user_params )
      redirect_to root_url, notice: "Cambios guardados"
    else
      render action: 'edit'
    end
	end

	def destroy
		
	end

	private
		def user_params
			params.require( :user ).permit( :username, :email, :password )
		end

		def get_user
			@user = User.find( params[:id] )
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ResetpasswordSorcery</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<% flash.each do |name, msg| %>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    <% end %>
	<div class="login">
		<% if current_user %>
			<div>
				<%= link_to current_user.username, :logout %>
			</div>
		<% else %>
			<div>
				<%= link_to "login", "sessions/new" %>
			</div>
		<% end %>
	</div>
	<%= yield %>

</body>
</html>

app/views/password_resets/create.html.erb
<h1>PasswordResets#create</h1>
<p>Find me in app/views/password_resets/create.html.erb</p>

app/views/password_resets/edit.html.erb
<h1>Choose a new password</h1>
<%= form_for @user, :url => password_reset_path(@user), :html => {:method => :put} do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
    
      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    
  <div class="field">
    <%= f.label :email %><br />
    <%= @user.email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
    <%= hidden_field_tag :token, @token %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/password_resets/new.html.erb
<%= form_tag password_resets_path, :method => :post do %>
  <div class="field">
    <%= label_tag :email %><br />
    <%= text_field_tag :email %> <%= submit_tag "Reset my password!" %>
  </div>
<% end %>

app/views/password_resets/update.html.erb
<h1>PasswordResets#update</h1>
<p>Find me in app/views/password_resets/update.html.erb</p>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
	<% if @user.errors.any? %>
		<div class="errors">
			<h2>Datos invalidos</h2>
			<ul>
				<% for msj in @user.errors.full_messages %>
					<li><%= msj %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<div class="field">
		<%= f.label :username %>
		<%= f.text_field :username %>
	</div>

	<div class="field">
		<%= f.label :email %>
		<%= f.text_field :email %>
	</div>

	<div class="field">
		<%= f.label :pasaword %>
		<%= f.password_field :password %>
	</div>

	<div class="field">
		<%= f.label :password_confirmation %>
		<%= f.password_field :password_confirmation %>
	</div>

	<div class="actions"><%= f.submit %></div>
<% end %>

app/views/users/edit.html.erb
<%= render 'form' %>

app/views/users/index.html.erb
<h1>Lista de usuarios</h1>
<% @users.each do |u| %>
	<div class="user">
		<%= link_to u.username, edit_user_path(u) %>
		<%= u.email %>
	</div>
<% end %>

app/views/users/new.html.erb
<%= render 'form' %>